config-version: 2
name: 'amplitude'
version: '1.2.0'
require-dbt-version: [">=1.3.0", "<3.0.0"]
models:
  amplitude:
    intermediate:
      +schema: int_amplitude
    +schema: amplitude
    staging:
      +schema: _source_amplitude
      materialized: table
      tmp:
        materialized: view

vars:
  amplitude:
    event_type: "{{ source('amplitude', 'event_type') }}"
    event: "{{ source('amplitude', 'event') }}"
    event_properties_to_pivot: []  # list of events properties from the event table (in the event source table, event_properties)  to pivot out into columns in amplitude__event_enhanced
    group_properties_to_pivot: []  # list of group properties from the event table (in the event source table, group_properties)  to pivot out into columns in amplitude__event_enhanced
    user_properties_to_pivot: []  # list of user properties from the event table (in the event source table, user_properties)  to pivot out into columns in amplitude__event_enhanced