name: 'amplitude_integration_tests'
version: '0.7.0'
config-version: 2
profile: 'integration_tests'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +schema: "{{ 'amplitude_sqlw' if target.name == 'databricks-sql' else 'amplitude' }}"
  # +schema: "amplitude_{{ var('directed_schema','dev') }}"

vars:
  amplitude_source:
    amplitude_event_identifier: "amplitude_event_data"
    amplitude_event_type_identifier: "amplitude_event_type_data"
    amplitude_schema: amplitude_integration_tests_5

seeds:
  amplitude_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    amplitude_event_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        app: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        amplitude_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        event_type_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        project_name: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        schema: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        session_id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'varchar(100)' if target.name in ('redshift', 'postgres') else 'string' }}"
    amplitude_event_type_data:
      +column_types:
        id: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        project_name: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        event_properties: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        group_properties: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
        user_properties: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    amplitude_event_bq_json_data:
      +enabled: "{{ target.type == 'bigquery' }}"
      +column_types:
        id: "INT64"
        app: "INT64"
        amplitude_id: "INT64"
        event_type_id: "INT64"
        project_name: "INT64"
        schema: "INT64"
        session_id: "INT64"
        user_id: string
        event_properties: json
        group_properties: json
        user_properties: json

flags:
  send_anonymous_usage_stats: False
